// <auto-generated />
namespace LojaSapatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _201923092150 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201923092150));
        
        string IMigrationMetadata.Id
        {
            get { return "201909240050265_201923092150"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
