// <auto-generated />
namespace LojaSapatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _201930091912 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201930091912));
        
        string IMigrationMetadata.Id
        {
            get { return "201909302212105_201930091912"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
