// <auto-generated />
namespace LojaSapatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _21929091637 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_21929091637));
        
        string IMigrationMetadata.Id
        {
            get { return "201909291938151_21929091637"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
