// <auto-generated />
namespace LojaSapatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _220920191610 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_220920191610));
        
        string IMigrationMetadata.Id
        {
            get { return "201909221910464_220920191610"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
